<?php

/**
 * @file
 * Contains bhcc_central_hub.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bhcc_central_hub_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bhcc_central_hub module.
    case 'help.page.bhcc_central_hub':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Central Hub interface') . '</p>';
      return $output;

    default:
  }
}
