<?php

/**
 * @file
 * Hook implementations.
 */

use Drupal\Core\Render\Element;
use Drupal\webform\Plugin\WebformHandlerInterface;


/**
 * Implements hook_theme().
 */
function localgov_forms_theme() {
  return [
    // Form element: localgov_webform_uk_address.
    'localgov_forms_uk_address_lookup' => [
      'render element' => 'element',
    ],
    // Form element: webform_uk_address.
    'localgov_forms_uk_address' => [
      'render element' => 'element',
    ],
    // Webform Handler Email summary
    'webform_handler_localgov_forms_email_summary' => [
      'variables' => ['settings' => NULL, 'handler' => NULL ],
    ],

  ];
}

/**
 * Prepares variables for the Address lookup element template.
 *
 * Makes sub-elements available within the `content` variable.  Mostly lifted
 * from _template_preprocess_webform_composite().
 */
function template_preprocess_localgov_forms_uk_address_lookup(array &$variables) {

  $element = $variables['element'];
  foreach (Element::children($element) as $key) {
    if (!isset($element[$key]['#access']) || $element[$key]['#access']) {
      $variables['content'][$key] = $element[$key];
    }
  }

  $variables['flexbox'] = $element['#flexbox'] ?? FALSE;
}

/**
 * Prepares variables for the UK address element template.
 */
function template_preprocess_localgov_forms_uk_address(array &$variables) {

  template_preprocess_localgov_forms_uk_address_lookup($variables);
}

/**
 * Implements hook_preprocess_hook() for hook_preprocess_webform().
 */
function localgov_forms_preprocess_webform(array &$variables) {
  $variables['#attached']['library'][] = 'localgov_forms/localgov_forms.form_errors';
}

/**
 *
 */
function localgov_forms_webform_handler_invoke_pre_save_alter( WebformHandlerInterface $handler, array &$args) {

  $configuration = $handler->getConfiguration();

  // Configuration id.
  $configuration_id = $configuration["id"];


  if ($configuration_id === 'localgov_forms_email' && ($configuration['settings']['attachments'] ?? FALSE)) {
    $webform = $handler->getWebform();
    $element_attachments = $handler->getWebform()->getElementsManagedFiles();

    array_walk($element_attachments, function($element_id) use($webform) {
      $element_properties = $webform->getElement($element_id);
      $element_properties['#format'] = 'name'; // Fixed file format.
      $webform->setElementProperties($element_id, $element_properties);
    });
  }


}