<?php

/**
 * @file
 * Hook implementations.
 */

/**
 * Implements hook_theme().
 */
function localgov_forms_theme() {
  return [
    'localgov_forms_uk_address' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Prepares variables for BHCC Webform templates.
 *
 * Default template: localgov-forms-uk-address.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 */
function template_preprocess_localgov_forms_uk_address(array &$variables) {
  // Here you can get the composite element and alter it.
  Drupal::moduleHandler()->loadInclude('webform', 'inc', 'includes/webform.theme.template');

  _template_preprocess_webform_composite($variables);
}

/**
 * Implements hook_preprocess_hook() for hook_preprocess_webform().
 */
function localgov_forms_preprocess_webform(array &$variables) {
  $variables['#attached']['library'][] = 'localgov_forms/localgov_forms.form_errors';
}
