<?php

/**
 * @file
 * LocalGov Forms Date module.
 */

/**
 * Implements hook_theme().
 */
function localgov_forms_date_theme() {
  return [
    'localgov_forms_date' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Datetime Form preprocess function.
 */
function localgov_forms_date_preprocess_datetime_form(array &$variables) {
  // Check that this is a localgov_forms_date form element.
  $variables['attributes']['class'][] = 'localgov-forms-date';
  $variables['#attached']['library'][] = 'localgov_forms_date/localgov_forms_date';
}
