<?php

/**
 * @file
 * LocalGov Forms Date module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Utility\WebformElementHelper;

/**
 * Implements hook_theme()
 */
function localgov_forms_date_theme() {
  return [
    'localgov_forms_date' => [
      'render element' => 'element',
    ],
  ];
}


/**
 * Implements hook_web_element_alter().
 */
function localgov_forms_webform_element_localgov_forms_date_alter(array &$element, FormStateInterface $form_state, array $context) {

  // We want our callback to trigger
  // on localgov_forms_date webform elements.
  $webform_key = [
    'localgov_forms_date',
  ];

  if (isset($element['#webform_key'], $webform_key)) {
    // Insert the validation at the top so this check
    // gets done first.
    array_unshift($element['#element_validate'], [
      '\Drupal\localgov_forms_date\Validate\LocalgovFormsDateValidateConstraint',
      'validate',
    ]);
  }

}
/**
 * Prepares variables for datetime form element templates.
 *
 * The datetime form element serves as a wrapper around the date element type,
 * which creates a date and a time component for a date.
 *
 * Default template: datetime-form.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 *     Properties used: #title, #value, #options, #description, #required,
 *     #attributes.
 *
 * @see form_process_datetime()
 */
function template_preprocess_localgov_forms_date(&$variables) {
  $element = $variables['element'];

  $variables['attributes'] = [];

  if (isset($element['#id'])) {
    $variables['attributes']['id'] = $element['#id'];
  }
  if (!empty($element['#attributes']['class'])) {
    $variables['attributes']['class'] = (array) $element['#attributes']['class'];
  }

  $variables['content'] = $element;

  // Add instructional text describing the required date and time formats.
  // This will be hidden on JavaScript-enabled browsers that have a native
  // datepicker.
  if (!empty($element['#date_date_format'])) {
    $placeholder_date = 'YYYY-MM-DD';
    $variables['attributes']['data-drupal-field-elements'] = 'date' . ($element['#date_time_element'] === 'none' ? '' : '-time');
    $date_format = is_array($element['#date_date_format']) ? $element['#date_date_format'][0] : date($element['#date_date_format']);
    $variables['content']['date']['#attributes']['placeholder'] = $placeholder_date;
    $help_date = t('Enter the date using the format @placeholder_date (e.g., @date_format).', ['@date_format' => $date_format, '@placeholder_date' => $placeholder_date]);
    $variables['content']['date']['#attributes']['data-help'] = $help_date;

    // Include time formatting instructions when a time input is present.
    if (!empty($element['#date_time_format'])) {
      $placeholder_time = 'hh:mm:ss';
      $time_format = is_array($element['#date_time_format']) ? $element['#date_time_format'][0] : date($element['#date_time_format']);
      $variables['content']['time']['#attributes']['placeholder'] = $placeholder_time;
      $help_time = t('Enter the time using the format @placeholder_time (e.g., @time_format).', ['@time_format' => $time_format, '@placeholder_time' => $placeholder_time]);
      $variables['content']['time']['#attributes']['data-help'] = $help_time;
    }
  }
}

/**
 * Prepares variables for datetime form wrapper templates.
 *
 * Default template: datetime-wrapper.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 *     Properties used: #title, #children, #required, #attributes.
 */
function template_preprocess_localgov_forms_date_wrapper(&$variables) {
  $element = $variables['element'];

  if (!empty($element['#title'])) {
    $variables['title'] = $element['#title'];
    // If the element title is a string, wrap it a render array so that markup
    // will not be escaped (but XSS-filtered).
    if (is_string($variables['title']) && $variables['title'] !== '') {
      $variables['title'] = ['#markup' => $variables['title']];
    }
  }

  // Suppress error messages.
  $variables['errors'] = NULL;

  $variables['description'] = NULL;
  if (!empty($element['#description'])) {
    $description_attributes = [];
    if (!empty($element['#id'])) {
      $description_attributes['id'] = $element['#id'] . '--description';
    }
    $description_attributes['data-drupal-field-elements'] = 'description';
    $variables['description'] = $element['#description'];
    $variables['description_attributes'] = new Attribute($description_attributes);
  }

  $variables['required'] = FALSE;
  // For required datetime fields 'form-required' & 'js-form-required' classes
  // are appended to the label attributes.
  if (!empty($element['#required'])) {
    $variables['required'] = TRUE;
  }
  $variables['content'] = $element['#children'];
}
