<?php

/**
 * @file
 * Contains customisations for the webform module.
 */

 module_load_include('inc', 'webform', 'includes/webform.theme.template');

 /**
  * Implements hook_theme().
  */
function bhcc_webform_date_theme() {
  return [
    'bhcc_webform_date' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Prepares variables for BHCC Webform templates.
 * 
 * Default template: bhcc_webform_date.html.twig.
 * 
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element. 
 */
function template_preprocess_bhcc_webform_date(array &$variables) {
  // Here you can get the composite element and alter it.
  _template_preprocess_webform_composite($variables);
}

